name: .NET Build and Test (More Platforms)

on:
  workflow_call:
  workflow_dispatch:
  push:
    paths:
      - '**.csproj'
      - '**.cs'
      - '**/Directory.Build.props'
      - '.github/workflows/test.yaml'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        tfm: [net10.0, net8.0, net6.0, net48]
        exclude:
          - os: ubuntu-latest
            tfm: net48
          - os: macos-latest
            tfm: net48
    runs-on: ${{ matrix.os }}
    env:
      TFMS: ${{ matrix.tfm }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: |
            10.0.x
            8.0.x
            6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build -- --retry-failed-tests 3 --report-trx --no-progress

  native-aot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Publish NativeAOT tests
        run: >
          dotnet publish tests/Configuration.Writable.Tests/Configuration.Writable.Tests.csproj
          --configuration Release
          --framework net10.0
          --runtime linux-x64
          --self-contained true

      - name: Run NativeAOT tests
        run: >
          tests/Configuration.Writable.Tests/bin/Release/net10.0/linux-x64/publish/Configuration.Writable.Tests
          --treenode-filter '/*/*/*/*JsonAot*'
          --no-progress
